[project]
name = "pointcloudsimilarity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tiago Tavares", email = "tiagoft@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.4.1",
    "faiss-gpu-cu12>=1.13.0",
    "gensim>=4.4.0",
    "numpy>=2.3.4",
    "pot>=0.9.6.post1",
    "pytest>=9.0.1",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "sentence-transformers>=5.1.2",
    "transformers>=4.57.3",
    "umap-learn>=0.5.9.post2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "pytest-benchmark>=5.2.3",
    "scikit-learn>=1.7.2",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]

[tool.pytest.ini_options]
addopts = "--benchmark-columns=mean,min,max,stddev"
